export const fontFamilies = [
  // Classic web-safe fonts
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Times New Roman", value: "Times New Roman, serif" },
  { label: "Courier New", value: "Courier New, monospace" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Verdana", value: "Verdana, sans-serif" },
  { label: "Tahoma", value: "Tahoma, sans-serif" },
  { label: "Trebuchet MS", value: "Trebuchet MS, sans-serif" },
  { label: "System UI", value: "system-ui, -apple-system, sans-serif" },

  // Extended web-safe fonts
  { label: "Helvetica", value: "Helvetica, sans-serif" },
  { label: "Palatino", value: "Palatino Linotype, Palatino, serif" },
  { label: "Garamond", value: "Garamond, serif" },
  { label: "Comic Sans MS", value: "Comic Sans MS, cursive, sans-serif" },
  { label: "Impact", value: "Impact, Charcoal, sans-serif" },
  { label: "Lucida Console", value: "Lucida Console, Monaco, monospace" },
  {
    label: "Lucida Sans",
    value: "Lucida Sans Unicode, Lucida Grande, sans-serif",
  },
  { label: "Cambria", value: "Cambria, serif" },
  { label: "Candara", value: "Candara, sans-serif" },
  { label: "Calibri", value: "Calibri, sans-serif" },
  { label: "Optima", value: "Optima, sans-serif" },
  { label: "Rockwell", value: "Rockwell, serif" },
  { label: "Monaco", value: "Monaco, monospace" },
  { label: "Consolas", value: "Consolas, monospace" },
  { label: "Segoe UI", value: "Segoe UI, sans-serif" },

  // Popular Google Fonts (need to be imported via CSS/Google Fonts API)
  { label: "Roboto", value: "Roboto, sans-serif" },
  { label: "Open Sans", value: "Open Sans, sans-serif" },
  { label: "Lato", value: "Lato, sans-serif" },
  { label: "Montserrat", value: "Montserrat, sans-serif" },
  { label: "Poppins", value: "Poppins, sans-serif" },
  { label: "Raleway", value: "Raleway, sans-serif" },
  { label: "Nunito", value: "Nunito, sans-serif" },
  { label: "Merriweather", value: "Merriweather, serif" },
  { label: "Playfair Display", value: "Playfair Display, serif" },
  { label: "Source Sans Pro", value: "Source Sans Pro, sans-serif" },
  { label: "Ubuntu", value: "Ubuntu, sans-serif" },
  { label: "Fira Sans", value: "Fira Sans, sans-serif" },
  { label: "Inconsolata", value: "Inconsolata, monospace" },
  { label: "PT Sans", value: "PT Sans, sans-serif" },
  { label: "PT Serif", value: "PT Serif, serif" },
];

export const textSizes = [
  { label: "4pt", size: "4pt" },
  { label: "6pt", size: "6pt" },
  { label: "8pt", size: "8pt" },
  { label: "10pt", size: "10pt" },
  { label: "12pt", size: "12pt" },
  { label: "14pt", size: "14pt" },
  { label: "16pt", size: "16pt" },
  { label: "18pt", size: "18pt" },
  { label: "20pt", size: "20pt" },
  { label: "22pt", size: "22pt" },
  { label: "24pt", size: "24pt" },
  { label: "26pt", size: "26pt" },
  { label: "28pt", size: "28pt" },
  { label: "30pt", size: "30pt" },
  { label: "32pt", size: "32pt" },
  { label: "34pt", size: "34pt" },
  { label: "36pt", size: "36pt" },
  { label: "38pt", size: "38pt" },
  { label: "40pt", size: "40pt" },
  { label: "42pt", size: "42pt" },
  { label: "44pt", size: "44pt" },
  { label: "46pt", size: "46pt" },
  { label: "48pt", size: "48pt" },
];

export const headings = [
  { level: 1, label: "Heading 1", tag: "h1" },
  { level: 2, label: "Heading 2", tag: "h2" },
  { level: 3, label: "Heading 3", tag: "h3" },
  { level: 4, label: "Heading 4", tag: "h4" },
  { level: 5, label: "Heading 5", tag: "h5" },
  { level: 6, label: "Heading 6", tag: "h6" },
  { level: 0, label: "Paragraph", tag: "p" },
];
